config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :donations
    resources :payments


    resources :events, only: [:new, :create, :index, :edit, :update, :show] do
      resources :participants, only: [:index, :show, :edit, :update, :destroy]
      resources :participations, only: [:index, :show, :edit, :update, :destroy]
      resources :options, only: [:new, :create, :index, :edit, :update, :destroy]
      resources :tickets, only: [:new, :create, :index, :edit, :update, :destroy]
      member do
        patch 'publish'   # Met à jour le statut de l'évènement
        get 'extract_optn', to: 'documents#download_options_xlsx', as: 'download_options_xlsx'
        get 'extract_bib', to: 'documents#download_bib_numbers_xlsx', as: 'download_bib_numbers_xlsx'
      end
    end

    root to: "custom_pages#home"
    delete '/clear_event', to: 'events#clear_event', as: 'clear_event'
  end


  root to: "pages#home"

  devise_for :users

  resources :donations, only: [:new, :create]
  resources :payments, only: [:new, :create] do
    collection do
      get :success
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :participations, only: [:edit, :update, :show]

  resources :events, only: [:index, :show] do
    resources :participants, only: [:new, :create]
  end

  resources :participants do
    get "token"
  end

  get 'send_email/:token', to: 'participations#send_participation_message', as: :send_email


end

app/models/event.rb
class Event < ApplicationRecord
  STATUS_OPTIONS = ["brouillon", "publié", "en cours", "terminé", "annulé"]
  belongs_to :charity
  has_many :tickets, dependent: :destroy
  has_many :options, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :participations, through: :tickets
  has_many :orders, through: :participations
  has_one_attached :image
  validates :status, inclusion: { in: STATUS_OPTIONS }
  validates :name, presence: true
  validates :date, presence: true
  validates :location, presence: true



  scope :brouillon, -> { where(status: "brouillon") }
  scope :publies, -> { where(status: "publié") }
  scope :annules, -> { where(status: "annulé") }
  scope :termines, -> { where(status: "terminé") }
  scope :en_cours, -> { where(status: "en cours") }
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController
    before_action :set_events, only: [:index]
    before_action :set_event, only: [:edit, :update, :show, :publication, :publish]
    before_action :set_charity, only: [:show]
    before_action :set_tickets, only: [:show]
    before_action :publication, only: [:index, :show]

    def new
      @event = Event.new
    end

    def create
      @event = Event.new(event_params)
      @event.date = Date.parse(params[:event][:date])
      @event.charity = Charity.first
      @event.status = "brouillon"
      if @event.save
        redirect_to admin_event_path(@event)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def index
    end

    def show
      @event = Event.find(params[:id])
      session[:current_event] = @event.id
      @current_event = Event.find_by(id: session[:current_event])
      @total = 0
      @totalinscription = 0
      @totalalimentaire = 0
      @totalvestimentaire = 0
      @totalgoodies = 0
    end

    def edit
    end

    def update
      if @event.update(event_params)
        redirect_to admin_event_path(@event)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def publication

    end

    def publish
      if @event.update(event_params)
        redirect_to admin_event_path(@event), notice: "Statut modifié avec succès."
      else
        render :publication, alert: "Erreur lors du changement de statut de l'évènement."
      end
    end

    def clear_event
      @current_event = nil
      redirect_to admin_events_path
    end

    private


    def event_params
      params.require(:event).permit(:name, :description, :date, :status, :location, :image)
    end

    def set_events
      @events = Event.all
    end

    def set_event
      @event = Event.find(params[:id])
    end

    def set_tickets
      @tickets = @event.tickets
    end

    def set_charity
      @charity = @event.charity
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
skip_before_action :authenticate_user!

  def index
    @events = Event.publies

  end

  def show
    # @token = Participant.token
    @event = Event.find(params[:id])

    @tickets = Ticket.where(event_id: @event.id)
  end



end

app/views/admin/events/_top_navbar.html.erb
   <%= link_to 'détails', admin_event_path(@event), id: "navbar-link" %>
   <%= link_to 'tickets', admin_event_tickets_path(@event), id: "navbar-link" %>
   <%= link_to 'options', admin_event_options_path(@event), id: "navbar-link" %>

app/views/admin/events/discarded.html.erb
<div class="event-content-container">
<%= link_to "revenir à la liste", admin_event_path %>

<h1><%= Event.count %> Anciens évènements</h1>
<h2>Évènements terminés</h2>
<% @events.termines.each do |event|%>
<p>___________________________</p>
<%= event.name  %>
<%= event.description %>
<%= event.date %>
<%= link_to "ouvrir", admin_event_path(event) %>
<% end %>
<p>___________________________</p>

</div>

app/views/admin/events/edit.html.erb
<div class="event-content-container">
  <h1 class="event-title">Modifier l'évènement</h1>

  <%= simple_form_for @event, url: admin_event_path(@event), method: :patch, html: { class: 'event-form-container' } do |f| %>
    <div class="mb-3">
      <%= f.input :name, label: "Nom de l'évènement", input_html: { class: 'form-control' } %>
    </div>
    <div class="mb-3">
      <%= f.input :description, as: :text, label: "Description", input_html: { class: 'form-control' } %>
    </div>
    <div class="mb-3">
      <%= f.input :location, label: "Lieu", input_html: { class: 'form-control' } %>
    </div>
    <div class="mb-3">
      <%= f.input :image, as: :file, label: "Changer l'image", input_html: { class: 'form-control' } %>
    </div>
    <div class="mb-3">
      <%= f.input :date, as: :date, html5: true, input_html: { class: 'form-control' } %>
    </div>
    <div class="mb-3">
      <%= f.button :submit, "Enregistrer", class: "rounded-button primary event-action-button" %>
    </div>
  <% end %>
</div>

app/views/admin/events/index.html.erb
<div class="event-content-container">
  <h1><%= Event.publies.count + Event.brouillon.count %> évènements dans la base</h1>

  <h2>Nouvel évènement</h2>
  <%= link_to "Créer un évènement", new_admin_event_path, class: "btn btn-rose event-action-button" %>

  <hr>


<% if @events.brouillon.any? %>
  <h2>En cours de rédaction</h2>
  <div class="card-container">
    <% @events.brouillon.each do |event| %>
      <div class="card-event">
        <% if event.image.attached? %>
          <%= cl_image_tag event.image.key, class: "event-image" %>
        <% else %>
          <%= image_tag "logo.png", class: "event-image" %>
        <% end %>
        <h3><%= event.name %></h3>
        <p><%= truncate(event.description, length: 100) %></p>
        <p><strong>Date :</strong> <%= event.date %></p>
        <%= link_to "Ouvrir", admin_event_path(event), class: "btn btn-rose event-action-button" %>
      </div>
    <% end %>
  </div>
  <hr>
<% end %>



  <h2>Publiés</h2>
  <div class="card-container">
    <% @events.publies.each do |event| %>
      <div class="card-event">
        <% if event.image.attached? %>
          <%= cl_image_tag event.image.key, class: "event-image" %>
        <% else %>
          <%= image_tag "logo.png", class: "event-image" %>
        <% end %>
        <h3><%= event.name %></h3>
        <p><%= truncate(event.description, length: 100) %></p>
        <p><strong>Date :</strong> <%= event.date %></p>
        <%= link_to "Ouvrir", admin_event_path(event), class: "btn btn-rose event-action-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/events/new.html.erb
<div class="event-content-container">
  <h1 class="event-title">Créer un évènement</h1>

  <%= simple_form_for @event, url: admin_events_path, method: :post, html: { class: 'event-form-container' } do |f| %>
    <div class="mb-3">
      <%= f.input :name, label: "Nom de l'évènement", input_html: { class: 'form-control' } %>
    </div>
    <div class="mb-3">
      <%= f.input :description, as: :text, label: "Description", input_html: { class: 'form-control' } %>
    </div>
    <div class="mb-3">
      <%= f.input :location, label: "Lieu", input_html: { class: 'form-control' } %>
    </div>
    <div class="mb-3">
      <%= f.input :date, as: :date, html5: true, input_html: { class: 'form-control' } %>
    </div>
    <%= f.input :image, as: :file, label: "Photo", input_html: { class: 'form-control' } %>
    <div class="mb-3">
      <%= f.button :submit, "Enregistrer", class: "rounded-button primary event-action-button" %>
    </div>
  <% end %>
</div>

app/views/admin/events/publication.erb
<div class="event-content-container">

  <h1 class="event-title">Modifier le statut de l'évènement</h1>
  <ul class="event-info-list">
    <li class="event-info-item">Brouillon : l'évènement n'apparaît que pour vous</li>
    <li class="event-info-item">Publié : l'évènement est visible, et les participants peuvent s'inscrire</li>
  </ul>

  <%= simple_form_for @event, url: publish_admin_event_path(@event), html: { class: 'event-form-container' } do |f| %>
    <%= f.input :status, collection: Event::STATUS_OPTIONS, as: :select, prompt: "Choisir un statut", input_html: { class: 'form-select' } %>
    <%= f.submit "Enregistrer", class: "event-action-button" %>
  <% end %>
</div>

app/views/admin/events/show.html.erb
<div class="container-home-dashboard" data-controller="countdown" data-countdown-event-date-value="<%= @event.date %> 10:00:00">
  <div class="header" >
     <div class="d-flex align-items-center justify-content-center">
        <h1 class="mx-3">Evénement dans :</h1>
        <p id="next-event" class="countdown-timer" style ="font-size: 2rem" data-countdown-target="timer"></p>
      </div>
      <div class="card-product">
        <%= link_to edit_admin_event_path(@event), class: "event-action-logo" do %>
          <i class="fas fa-edit event-edit-icon"></i>
        <% end %>
        <% if @event.image.attached? %>
          <%= cl_image_tag @event.image.key, class: "card-product img" %>
        <% else %>
          <%= image_tag "logo.png", class: "card-product img" %>
        <% end %>
        <div class="card-product-infos">
          <h1><%= @event.name %></h1>
          <p><%= @event.description %></p>
          <p><%= @event.date %></p>
        </div>
      </div>

    </div>

    <div class="card-product justify-content-center">
      <div style="margin: 16px">
        <h2 class="event-title">Statut de l'évènement</h2>
        <ul class="event-info-list">
          <li class="event-info-item" style="font-style: italic; font-size: 12px">Brouillon : l'évènement n'apparaît que pour vous</li>
          <li class="event-info-item" style="font-style: italic; font-size: 12px">Publié : l'évènement est visible, et les participants peuvent s'inscrire</li>
        </ul>
        <%= simple_form_for @event, url: publish_admin_event_path(@event) do |f| %>
          <%= f.input :status,label: false, collection: Event::STATUS_OPTIONS, as: :select, prompt: "Choisir un statut" %>
          <%= f.submit "Enregistrer", class:" btn-rose w-100" %>
        <% end %>
      </div>
    </div>

    <div class="affichage-des-chiffres">
      <div class="inscriptions">
        <h2> INSCRIPTIONS </h2>
        <h3>à la <%= @event.name %></h3>
        <p class="bandeau"><strong><%= @event.participations.count %> inscrits</strong></p>
        <ul>
          <% @tickets.each do |ticket| %>
          <li>
            <p><strong><%=ticket.name %> : </strong> <%=ticket.participations.count %> inscrits</p>
          </li>
          <% end %>
        </ul>
      </div>
      <div class="money">
        <h2>RECETTES</h2>
        <h3>grace à la <%= @event.name %></h3>

        <% @event.participations.each do |participation| %>
          <% @total += participation.total_amount %>
          <% @totalinscription += participation.ticket.unit_price %>
        <% end %>

        <% @event.orders.each do |order| %>

          <% if order.option.category === "Alimentaire" %>
            <% @totalalimentaire += order.option.unit_price * order.quantity %>
          <% end %>

          <% if order.option.category === "Vestimentaire" %>
            <% @totalvestimentaire += order.option.unit_price * order.quantity %>
          <% end %>

          <% if order.option.category === "Goodies" %>
            <% @totalgoodies += order.option.unit_price * order.quantity %>
          <% end %>

        <% end %>

        <p class="bandeau"><strong><%= @total %> €</strong></p>

        <ul>
          <li><p><strong>inscriptions : </strong><%= @totalinscription %> €</p></li>
          <li><p><strong>alimentaire : </strong><%= @totalalimentaire %> €</p></li>
          <li><p><strong>vestimentaire : </strong><%= @totalvestimentaire %> €</p></li>
          <li><p><strong>goodies : </strong> <%= @totalgoodies %> €</p></li>
        </ul>
      </div>
    </div>

     <div class="card-product justify-content-center">
      <div style="margin: 16px">
        <h2 class="event-title">Télécharger les données :</h2>
        <div class="d-flex justify-content-between">
          <%= link_to "Options", download_options_xlsx_admin_event_path, class: "btn btn-rose btn-download", data: { turbo: false } %>
          <%= link_to "N° de dossard", download_bib_numbers_xlsx_admin_event_path, class: "btn btn-rose btn-download", data: { turbo: false } %>
        </div>
      </div>
    </div>




</div>