config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :donations
    resources :payments


    resources :events, only: [:new, :create, :index, :edit, :update, :show] do
      resources :participants, only: [:index, :show, :edit, :update, :destroy]
      resources :participations, only: [:index, :show, :edit, :update, :destroy]
      resources :options, only: [:new, :create, :index, :edit, :update, :destroy]
      resources :tickets, only: [:new, :create, :index, :edit, :update, :destroy]
      member do
        patch 'publish'   # Met à jour le statut de l'évènement
        get 'extract_optn', to: 'documents#download_options_xlsx', as: 'download_options_xlsx'
        get 'extract_bib', to: 'documents#download_bib_numbers_xlsx', as: 'download_bib_numbers_xlsx'
      end
    end

    root to: "custom_pages#home"
    delete '/clear_event', to: 'events#clear_event', as: 'clear_event'
  end


  root to: "pages#home"

  devise_for :users

  resources :donations, only: [:new, :create]
  resources :payments, only: [:new, :create] do
    collection do
      get :success
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :participations, only: [:edit, :update, :show]

  resources :events, only: [:index, :show] do
    resources :participants, only: [:new, :create]
  end

  resources :participants do
    get "token"
  end

  get 'send_email/:token', to: 'participations#send_participation_message', as: :send_email


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
<div class="footer">
  <div>
    <a href="#" class="footer-logo"><i class="fa-brands fa-instagram reseaux"></i></a>
    <a href="#" class="footer-logo"><i class="fa-brands fa-facebook reseaux"></i></a>
    <a href="#" class="footer-logo"><i class="fa-brands fa-linkedin reseaux"></i></a>
  </div>


  <%= link_to "Admin", admin_root_path, class: "nav-link" %>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-calpin">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <div class="navbar-center collapse navbar-collapse" id="navbarSupportedContent"">
      <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <%= link_to "L'association", root_path, class: (params[:controller] == "pages" && params[:action] == "home") ? "nav-link active-bold" : "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Nos évènements", events_path, class: (params[:controller] == "events" || params[:controller] == "participants" || params[:controller] == "participations") ? "nav-link active-bold" : "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Faire un don", new_donation_path, class: (params[:controller] == "donations" && params[:action] == "new") ? "nav-link active-bold" : "nav-link" %>
          </li>
      </ul>
    </div>

    <a href="mailto:test@test.fr" class="nav-contact">Nous contacter</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  </div>
</div>

app/views/shared/_receipt.html.erb
<div class="receipt" style="background-color: var(--background-rose); border: 2px dotted #000; padding: 20px; margin: 0 auto; width: 50%; max-width: 400px;">
  <div style="border-bottom: 1px solid #000; padding-bottom: 10px; margin-bottom: 10px;">
    <p style="margin: 0; font-weight: bold;">Évènement : <%= participation.ticket.event.name %></p>
    <p style="margin: 0; font-weight: bold;">Billet : <%= participation.ticket.name %></p>
    <p style="margin: 0; text-align: right;"><%= number_to_currency(participation.ticket.unit_price, unit: "€") %></p>
  </div>

  <% ["Alimentaire", "Vestimentaire", "Autre", "Goodies"].each do |category| %>
    <% category_orders = participation.orders.select { |order| order.option.category == category } %>
    <% if category_orders.any? %>
      <div style="border-bottom: 1px solid #000; padding-bottom: 10px; margin-bottom: 10px;">
        <h5 style="margin: 0; text-align: left; text-transform: uppercase;"><%= category %></h5>
        <% category_orders.each do |order| %>
        <div style="display: flex; justify-content: space-between; margin: 5px 0;"> <!-- Spacing included -->
          <span><%= order.option.name %> x <%= order.quantity %></span>
          <span><%= number_to_currency(order.option.unit_price * order.quantity, unit: "€") %></span>
        </div>
      <% end %>
      </div>
    <% end %>
  <% end %>

  <div style="border-top: 2px solid #000; padding-top: 10px; font-weight: bold;">
    <div style="display: flex; justify-content: space-between;">
      <span>Total :</span>
      <span>
        <%= number_to_currency(
        participation.orders.sum { |order| order.option.unit_price * order.quantity } + participation.ticket.unit_price,
        unit: "€"
      ) %>

      </span>
    </div>
  </div>
</div>