config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :donations
    resources :payments


    resources :events, only: [:new, :create, :index, :edit, :update, :show] do
      resources :participants, only: [:index, :show, :edit, :update, :destroy]
      resources :participations, only: [:index, :show, :edit, :update, :destroy]
      resources :options, only: [:new, :create, :index, :edit, :update, :destroy]
      resources :tickets, only: [:new, :create, :index, :edit, :update, :destroy]
      member do
        patch 'publish'   # Met à jour le statut de l'évènement
        get 'extract_optn', to: 'documents#download_options_xlsx', as: 'download_options_xlsx'
        get 'extract_bib', to: 'documents#download_bib_numbers_xlsx', as: 'download_bib_numbers_xlsx'
      end
    end

    root to: "custom_pages#home"
    delete '/clear_event', to: 'events#clear_event', as: 'clear_event'
  end


  root to: "pages#home"

  devise_for :users

  resources :donations, only: [:new, :create]
  resources :payments, only: [:new, :create] do
    collection do
      get :success
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :participations, only: [:edit, :update, :show]

  resources :events, only: [:index, :show] do
    resources :participants, only: [:new, :create]
  end

  resources :participants do
    get "token"
  end

  get 'send_email/:token', to: 'participations#send_participation_message', as: :send_email


end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  has_many :participations
  has_and_belongs_to_many :options

  validates :name, presence: true
  validates :unit_price, presence: true
end

app/controllers/admin/tickets_controller.rb
module Admin
  class TicketsController < Admin::ApplicationController
    before_action :set_current_event, only: [:index, :show, :new, :edit]
    before_action :set_event, only: [:new, :create, :index, :edit, :update, :destroy]
    before_action :set_ticket, only:[:edit, :update, :destroy]
    before_action :set_tickets, only:[:index]
    def index
      @ticket = Ticket.new
    end

    def new
      if @event.status == "terminé"
        redirect_to admin_event_tickets_path(@event), alert: "Impossible de créer un ticket car l'évènement est terminé."
        return
      end
      @ticket = Ticket.new
    end

    def create
      @ticket = Ticket.create(ticket_params)
      @ticket.event = @event
      if @ticket.save
        redirect_to admin_event_tickets_path(@event)
      else
        render "/admin/tickets/new"
      end
    end

    def edit
      if @event.status == "terminé"
        redirect_to admin_event_tickets_path(@event), alert: "Impossible de modifier un ticket car l'évènement est terminé."
        return
      end
    end

    def update
      if @ticket.update(ticket_params)
        redirect_to admin_event_tickets_path(@event)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @ticket.destroy
        redirect_to admin_event_tickets_path(@event), notice: 'Ticket supprimé avec succès.'
      else
        redirect_to admin_event_tickets_path(@event), alert: 'Suppression impossible'
      end
    end

    private

    def set_current_event
      @current_event = Event.find_by(id: session[:current_event])
    end

    def ticket_params
      params.require(:ticket).permit(:name, :unit_price, :description, :remote)
    end

    def set_event
      @event = Event.find(params[:event_id])
    end

    def set_tickets
      @tickets = @event.tickets
    end

    def set_ticket
      @ticket = Ticket.find(params[:id])
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end
end

app/views/admin/tickets/_cardTicket.html.erb
<div class="card-ticket">
  <div style="height: 70px;">
    <h3><%= ticket.name %></h3>
  </div>
  <div style="height: 90px;">
    <p><%= truncate(ticket.description, length: 100) %></p>
  </div>
  <div>
    <p><strong>Prix :</strong> <%= ticket.unit_price %> €</p>
  </div>
  <div>
    <%= link_to "Modifier", edit_admin_event_ticket_path(@event, ticket), class: "btn btn-rose event-action-button" %>
  </div>
</div>

app/views/admin/tickets/_newTicket.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
Ajouter une course
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">nouveau ticket</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">


        <h1>Créer une course </h1>
        <%= simple_form_for [@event, @ticket], url: admin_event_tickets_path(@event), method: :post do |f| %>
          <%= f.input :name %>
          <%= f.input :description, as: :text %>
          <%= f.input :unit_price %>
          <%= f.input :present, as: :boolean %>
          <%= f.submit "Créer le ticket", class: "btn btn-primary" %>
        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-rose" data-bs-dismiss="modal">Fermer</button>
        <button type="button" class="btn btn-rose">Enregistrer</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/tickets/edit.html.erb
<div class="event-content-container">
  <h1>Modifier une course </h1>
  <%= simple_form_for [@event, @ticket], url: admin_event_ticket_path(@event, @ticket), method: :patch do |f| %>
  <%= f.input :name, label: "Intitulé du ticket" %>
  <%= f.input :description, as: :text, label: "Description" %>
  <%= f.input :unit_price, label: "Prix unitaire"%>
  <%= f.input :remote, as: :boolean, label: "Distanciel ?" %>
  <%= f.submit "Modifier le ticket", class: "btn btn-primary" %>
  <% end %>
  <%= link_to admin_event_ticket_path(@event, @ticket), 
    data: { turbo_method: :delete, turbo_confirm: 'Vous voulez vraiment supprimer ce ticket ?' }, 
    class: 'btn btn-danger' do %> Supprimer
  <% end %>
  <%= form_with url: admin_event_ticket_path(event_id: @event.id, id: @ticket.id), method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer ce ticket ?' } do %>
  <%= submit_tag 'Supprimer', class: 'btn btn-danger' %>
<% end %>
</div>

app/views/admin/tickets/index.html.erb
<div class="event-content-container">

  <h2>Les tickets de la <%= @event.name %></h2>
  <% if @event.tickets.any? %>
    <div class="container">
      <div class="row d-flex">
        <% @tickets.each do |ticket| %>
            <span class="col-4 my-2">
              <%= render 'admin/tickets/cardTicket', ticket: ticket %>
            </span>
        <% end %>
       </div>
    </div>
  <% else %>
    <h2>Vous n'avez pas encore créé de tickets.</h2>
  <% end %>

  <h2>Ajouter un ticket</h2>
  <%= link_to 'Créer un nouveau ticket', new_admin_event_ticket_path(@event), class: 'btn btn-rose event-action-button' %>
</div>

app/views/admin/tickets/new.html.erb
<div class="event-content-container">
<h1>Ajouter une course </h1>
<%= simple_form_for [@event, @ticket], url: admin_event_tickets_path(@event), method: :post do |f| %>
  <%= f.input :name, label: "Intitulé du ticket" %>
  <%= f.input :description, as: :text, label: "Description" %>
  <%= f.input :unit_price, label: "Prix unitaire"%>
  <%= f.input :remote, as: :boolean, label: "Distanciel ?" %>
  <%= f.submit "Créer le ticket", class: "btn btn-primary" %>
<% end %>
</div>